os: osx
osx_image: xcode12.2
language: swift
script: xcodebuild clean build test -project EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" -destination 'platform=iOS Simulator,name=iPhone 11.0' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO